version: '3.9'
services:
    baype-security-ms:
        container_name: user-services-ms
        build:
            context: ./
            dockerfile: Dockerfile
        image: user-services-ms:latest
        #cpus: "0.5"
        #mem_reservation: "10M"
        #mem_limit: "250M"
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                limits:
                    cpus: '0.25'
                    memory: 250M
                reservations:
                    cpus: '0.1'
                    memory: 30M
    #product-server:
    #    container_name: product-server
    #    build:
    #        context: docker-product-server
    #        dockerfile: Dockerfile
    #    image: product-server:latest
    #    ports:
    #        - 19999:9999
    #    networks:
    #        - spring-cloud-network
    #    deploy:
    #        restart_policy:
    #            condition: on-failure
    #            delay: 3s
    #            max_attempts: 5
    #            window: 60s
networks:
    spring-cloud-network:
        driver: bridge